// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCz3rjZ5z6BQheyT_cNUK9gryqb_XhmY',
    appId: '1:304078099310:web:9375f7c460e21751f4a77f',
    messagingSenderId: '304078099310',
    projectId: 'linkme-back-mtel',
    authDomain: 'linkme-back-mtel.firebaseapp.com',
    storageBucket: 'linkme-back-mtel.firebasestorage.app',
    measurementId: 'G-5128MGNZH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCai06Cuu7k46a-LM60WAMGXkhU_POPCQw',
    appId: '1:304078099310:android:89db53f3fda75e7cf4a77f',
    messagingSenderId: '304078099310',
    projectId: 'linkme-back-mtel',
    storageBucket: 'linkme-back-mtel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCggj8jTU2xbn1XP3bs7kbRtjpn5JGGshY',
    appId: '1:304078099310:ios:1c10be7d203c4bd1f4a77f',
    messagingSenderId: '304078099310',
    projectId: 'linkme-back-mtel',
    storageBucket: 'linkme-back-mtel.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCggj8jTU2xbn1XP3bs7kbRtjpn5JGGshY',
    appId: '1:304078099310:ios:1c10be7d203c4bd1f4a77f',
    messagingSenderId: '304078099310',
    projectId: 'linkme-back-mtel',
    storageBucket: 'linkme-back-mtel.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFCz3rjZ5z6BQheyT_cNUK9gryqb_XhmY',
    appId: '1:304078099310:web:27f39a39a2c49603f4a77f',
    messagingSenderId: '304078099310',
    projectId: 'linkme-back-mtel',
    authDomain: 'linkme-back-mtel.firebaseapp.com',
    storageBucket: 'linkme-back-mtel.firebasestorage.app',
    measurementId: 'G-LWV23SBS8E',
  );
}
